apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-pubsub-emulator
spec:
  selector:
    matchLabels:
      app: gcp-pubsub-emulator
  replicas: 1
  template:
    metadata:
      labels:
        app: gcp-pubsub-emulator
    spec:
      containers:
        - name: gcp-pubsub-emulator
          image: quzhi65222714/gcp-pubsub-emulator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          resources: {}
