apiVersion: v1
kind: Service
metadata:
    name: "gcp-pubsub-emulator"
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    app: gcp-pubsub-emulator
  type: LoadBalancer
status:
  loadBalancer: {}
