apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: fiber-otel
spec:
  ports:
    - name: "8090"
      port: 8080
      targetPort: 8080
  selector:
    app: fiber-otel
  type: LoadBalancer
status:
  loadBalancer: {}
