apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.speedscale.com/inject: "true"
    sidecar.speedscale.com/tls-out: "true"
    replay.speedscale.com/mode: "generator-only"
  name: api-b
spec:
  selector:
    matchLabels:
      app: api-b
  replicas: 1
  template:
    metadata:
      labels:
        app: api-b
    spec:
      containers:
        - name: api-b
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 50Mi
            requests:
              cpu: 200m
              memory: 50Mi
          ports:
            - containerPort: 3010
          env:
            - name: PUBSUB_EMULATOR_HOST
              value: "gcp-pubsub-emulator.default.svc.cluster.local:8085"
