mode: deployment

config:
  exporters:
    # logging:
    #   loglevel: info
    coralogix:
      # The Coralogix traces ingress endpoint
      endpoint: "tracing-ingress.coralogix.com:9443"
      # Coralogix private key (fill and uncomment below)
      # private_key: ""
      # Traces emitted by this OpenTelemetry exporter should be tagged
      # in Coralogix with the following application and subsystem names
      application_name: "OtelTest"
      subsystem_name: "otel"
  service:
    pipelines:
      traces:
        receivers: [ otlp ]
        processors: [ ]
        exporters: [ logging,coralogix ]
