mode: deployment

config:
  exporters:
    logging:
      loglevel: info
    coralogix:
      # The Coralogix traces ingress endpoint
      endpoint: "tracing-ingress.coralogix.us:9443"
      # Coralogix private key (fill below)
      private_key: ""
      # Traces emitted by this OpenTelemetry exporter should be tagged
      # in Coralogix with the following application and subsystem names
      application_name: "us-central1-prod1"
      subsystem_name: "traces"
  service:
    pipelines:
      traces:
        receivers: [ otlp ]
        processors: [ ]
        exporters: [ logging,coralogix ]
        # exporters: [ logging ]
